### DISCUSSION TITLE
[FEATURE] Readonly mode

### DISCUSSION THREAD

**Discussion by brauliobo** [shentao/vue-multiselect#1788] [Ideas]
For the usecase of showing tags without having a dropdown, the input and the option to remove each tag, a `readonly` mode would fit it.

One simple CSS for it:
```scss
  .multiselect {
    width: auto;
    cursor: auto;

    .multiselect__select, .multiselect__tag-icon, .multiselect__content-wrapper, .multiselect__placeholder {
      display: none !important;
    }
    .multiselect__tags {
      border: none;
      .multiselect__tag {
        padding-right: 10px;
      }
    }
  }
```
