### ISSUE TITLE
Fix loading spinner's position

### ISSUE THREAD

**Issue by DrDreave** [shentao/vue-multiselect#1300]
### Reproduction Link
[Vue Multiselect](https://vue-multiselect.js.org/#sub-asynchronous-select)

### Steps to reproduce
1. Trigger loading state in asynchronous select

### Expected behaviour
The loading spinner should be positioned the same way as the dropdown arrow so there is a smooth transition between both states.

![image](https://user-images.githubusercontent.com/5685439/87126413-6c83ac00-c28c-11ea-838a-7f456662213f.png)

### Actual behaviour
There is an offset between the spinner and the arrow.

![image](https://user-images.githubusercontent.com/5685439/87126151-0139da00-c28c-11ea-87a8-44fb07ea542b.png)

### Proposed fix
```css
.multiselect__spinner {
  /* Same values as for .multiselect__select */
  width: 40px;
  height: 38px;
}
```
