### ISSUE TITLE
Allow disabled options to have a tooltip.

### ISSUE THREAD

**Issue by erenard** [shentao/vue-multiselect#1314]
My client wants a tooltip to show the reason why an option is disabled.
Unfortunately it won't work with disabled options.
Please note that enabled option can have a tooltip without problem.

### Reproduction Link
https://jsfiddle.net/Timmy469/L3vxoeg2/3/

### Steps to reproduce
Hover the disabled option with the mouse cursor.

### Expected behavior
The tooltip shows up

### Actual behavior
The tooltip doesn't show up

**Comment by Yoduh** [comment]
Stumbled on this issue today and made a workaround with CSS:
```css
.multiselect__option--disabled {
  cursor: pointer; /* optional */
  pointer-events: auto;
}
```

https://jsfiddle.net/xvbq91po/2/
