### ISSUE TITLE
Optiongroup children should be indented

### ISSUE THREAD

**Issue by mrleblanc101** [shentao/vue-multiselect#1474]
Currently, it's difficult to understand the relation between optiongroup children and their parent as the is no indentation.
The parent has a light grey background, but it's that it's a parent-children relationship. 

<img width="403" alt="Capture d’écran, le 2021-08-16 à 15 01 38" src="https://user-images.githubusercontent.com/17392251/129616044-4ba490de-08d6-4018-83a8-a8c70dc02f20.png">

I think the optiongroup children should be indented just like in regular select.
<img width="482" alt="Capture d’écran, le 2021-08-16 à 14 47 58" src="https://user-images.githubusercontent.com/17392251/129614586-87dc3095-caaa-4623-80a3-dea0d75dbb95.png">

I could do this with custom style, but optiongroup children are not nested inside their parent in the HTML and the children have no specific class, only the optiongroup parent has a class.

If I add padding to all element, then remove the padding for the optiongroup parent, this will affect my other multiselect that do not have optiongroup. There is no global class on the component to know if it has optiongroup or not.

```scss
.multiselect__option {
    padding-left: 24px; // Add padding to every element
}
.multiselect__option--group {
    padding-left: 12px; // Remove padding to every parent
}
```

What it should be:
```scss
.multiselect__option--children {
    padding-left: 24px; // Add padding only to children
}
```
or 
```scss
.multiselect.has-option-group {
    .multiselect__option {
    padding-left: 24px; // Add padding to every element
    }
    .multiselect__option--group {
    padding-left: 12px; // Remove padding to every parent
    }
}
```

<img width="406" alt="Capture d’écran, le 2021-08-16 à 14 58 39" src="https://user-images.githubusercontent.com/17392251/129615669-ea3545e0-3266-463a-9df2-1128043d8953.png">
