### ISSUE TITLE
Override style with select disabled group label 

### ISSUE THREAD

**Issue by hon9g** [shentao/vue-multiselect#1486]
### Steps to reproduce

- Using slot named `option` like this
```html
<template slot="option"
                   slot-scope="{ option }">
  <a v-if="option.$groupLabel" >{{option.$groupLabel}}</a>
  <a v-else class="custom-option">
    <checkbox :value="Boolean(selectedArray.find(v => v === option.key))"
              :label="option.label"
              @input="onToggle(option.key)" />
  </a>
</template>
```
- Contain below code as scoped scss.
```scss
.multiselect__option {
    &.multiselect__option--group {
        &.multiselect__option--disabled {
                background: #FFF !important;
                a {
                    color:#000;
                    font-weight:700;
                    font-size:12px;
                }
        }
    }
}
```

### Expected behaviour
I want to override `.multiselect__option--disabled`'s css properties when it also has `.multiselect__option--group`.

### Actual behaviour
Not overrided at all.

**Comment by hon9g** [comment]
sloved!
/with
```scss
/deep/ .multiselect__option {
    &.multiselect__option--group {
        &.multiselect__option--disabled {
                background: #FFF !important;
                a {
                    color:#000;
                    font-weight:700;
                    font-size:12px;
                }
        }
    }
}
```
