### ISSUE TITLE
Color options

### ISSUE THREAD

**Issue by willtholke** [shentao/vue-multiselect#1628]
This library doesn't have any parameters for customizing the current CSS scheme. It'd be nice to customize the interface colors without manually changing the source code.

Example of fixed color-scheme:
```css
.multiselect__option--highlight {
    background: #41b883;
    outline: none;
    color: #fff;
}
```
